fix: true # default: false
parallel: true # default: false
format: progress # default: Standard::Formatter
default_ignores: false # default: true

ignore:
  - "bin/*"
  - "db/**/*"
  - "config/**/*"
  - "Guardfile"
  - "Rakefile"
  - "spec/**/*"
  - "test/**/*"
  - "*/**/*.jbuilder"
  - "Gemfile"
  - "config.ru"
